HOSTS: ${SHARED_DIR}/hostfile.txt
ORANGEFS_SPACK:
    package_name: orangefs
METADATA:
    HOSTS: 1-3
    META_DIR: ${PER_NODE_DIR}/orangefs_meta
SERVER:
    HOSTS: 1-3
    PVFS2TAB: ${SHARED_DIR}/pvfs2tab
    STORAGE_DIR: ${PER_NODE_DIR}/orangefs_data
    LOG: ${PER_NODE_DIR}/orangefs_server.log
    STRIPE_SIZE: 65536
    DISTRIBUTION_NAME: simple_stripe
    PVFS2_PORT: 3334
    # protocol can be tcp or ib
    PVFS2_PROTOCOL: tcp
CLIENT:
    HOSTS: 1-3
    PVFS2TAB: ${SHARED_DIR}/pvfs2tab
    MOUNT_POINT: ${SHARED_DIR}/pvfs2-mount
