HOSTS: ${SHARED_DIR}/hostfile.txt
ORANGEFS_SPACK:
    package_name: orangefs
META:
    HOSTS: 1-3
SERVER:
    HOSTS: 1-3
    PVFS2TAB: ${SHARED_DIR}/pvfs2tab
    STORAGE_DIR: /mnt/hdd/${USER}/pvfs2-storage
    STRIPE_SIZE: 65536
    DISTRIBUTION_NAME: simple_stripe
    PVFS2_PORT: 3334
    # protocol can be tcp or ib
    PVFS2_PROTOCOL: tcp
CLIENT:
    HOSTS: 1-3
    PVFS2TAB: ${SHARED_DIR}/pvfs2tab
    MOUNT_POINT: ${SHARED_DIR}/pvfs2-mount
