HOSTS: ${SCAFFOLD}/hostfile.txt
SSH:
  primary:
    username: cc
    port: 22
    key: scs_chameleon_pass
    key_dir: ${HOME}/.ssh
    dst_key_dir: /home/cc/.ssh
  github:
    hostname: 'github.com'
    key: id_rsa
    key_dir: ${HOME}/.ssh
    dst_key_dir: /home/cc/.ssh