HOSTS: ${SCAFFOLD}/hostfile.txt
SSH:
  username: cc
  port: 22
  key: scs_chameleon_pass
  key_dir: ${HOME}/.ssh
  dst_key_dir: /home/cc/.ssh
ssh_keys:
  github:
    key: id_rsa
    key_dir: ${HOME}/.ssh
    dst_key_dir: /home/cc/.ssh