version: "3"

services:
  pkg1:
    build: .
    links:
      - pkg2
    networks:
      - net
    hostname: pkg1
    stdin_open: true
    tty: true

  pkg2:
    build: .
    networks:
      - net
    hostname: pkg2
    stdin_open: true
    tty: true

networks:
  net:
    driver: bridge