#defaults:
#  - base_config
#  - _self_
data:
  aux_file: ##TEST_FILE##
  data_directory: ##DATASET_DIR##
  data_format: channels_last
  downsample: 1
  file: ##TRAIN_FILE##
  synthetic: False
framework:
  environment_variables:
    TF_XLA_FLAGS: --tf_xla_auto_jit=2
  inter_op_parallelism_threads: 2
  intra_op_parallelism_threads: 24
  name: tensorflow
mode:
  checkpoint_iteration: 500
  logging_iteration: 1
  name: train
  no_summary_images: False
  optimizer:
    gradient_accumulation: 1
    learning_rate: 0.0003
    loss_balance_scheme: light
    name: adam
  summary_iteration: 1
  weights_location:
network:
  batch_norm: True
  bias: True
  block_concat: False
  blocks_deepest_layer: 5
  blocks_final: 5
  blocks_per_layer: 2
  bottleneck_deepest: 256
  connections: concat
  conv_mode: 2D
  data_format: channels_last
  downsampling: max_pooling
  filter_size_deepest: 5
  growth_rate: 1
  n_initial_filters: 16
  name: uresnet
  network_depth: 6
  residual: True
  upsampling: interpolation
  weight_decay: 0.0
run:
  aux_iterations: 10
  aux_minibatch_size: 16
  compute_mode: CPU
  distributed: False
  id: test
  iterations: 1
  minibatch_size: 16
  output_dir: output/tensorflow/uresnet/test/
  precision: float32
  profile: False