SCAFFOLD: null
BASIC:
    SSH_PORT: 22
    SSH_USER: "${USER}"
    FSNAME: "lustrefs"
MANAGEMENT_SERVER:
    STORAGE: "/dev/sdb"
    MOUNT_POINT: "${SCAFFOLD}/lustre_mounts/mgt_mount"
    HOST: "10.0.2.15"
METADATA_SERVER:
    STORAGE: "/dev/sdc"
    MOUNT_POINT: "${SCAFFOLD}/lustre_mounts/mdt_mount"
    HOST: "10.0.2.15"
OBJECT_STORAGE_SERVERS:
    MOUNT_POINT_BASE: "${SCAFFOLD}/lustre_mounts/ost"
    HOSTFILE: "${SCAFFOLD}/oss_hosts.txt"
    OSTS:
        - "/dev/sdd"
CLIENT:
    MOUNT_POINT: "${SCAFFOLD}/lustre_mounts/client_mount"
    HOSTFILE: "${SCAFFOLD}/client_hosts.txt"