SCAFFOLD: null
DAOS_ROOT: ${DAOS_ROOT}
CONF:
  SERVER: ${SCAFFOLD}/daos_server.yaml
  AGENT: ${SCAFFOLD}/daos_agent.yaml
  CONTROL: ${SCAFFOLD}/daos_control.yaml
SERVER:
  name: daos_server
  access_points: ['localhost']
  port: 10001
  provider: ofi+tcp
  telemetry_port: 9191
  control_log_file: ${SCAFFOLD}/daos_server.log
  transport_config:
    allow_insecure: false
    ca_cert: ${SCAFFOLD}/daosCA/certs/daosCA.crt
    cert: ${SCAFFOLD}/daosCA/certs/server.crt
    client_cert_dir: ${SCAFFOLD}/daosCA/certs
    key: ${SCAFFOLD}/daosCA/certs/server.key
  engines:
    -
      targets: 1
      first_core: 0
      nr_xs_helpers: 0
      fabric_iface: eth0
      fabric_iface_port: 31416
      log_file: ${SCAFFOLD}/daos_engine.0.log
      env_vars:
        - FI_SOCKETS_MAX_CONN_RETRY=1
        - FI_SOCKETS_CONN_TIMEOUT=2000
      storage:
        -
          class: ram
          scm_size: 1
          scm_mount: '${SCAFFOLD}/scm_test'
        -
          class: file
          bdev_size: 1
          bdev_list: ['${SCAFFOLD}/file_test']
AGENT:
  name: daos_server
  access_points: ['localhost']
  port: 10001
  transport_config:
    allow_insecure: false
    ca_cert: ${SCAFFOLD}/daosCA/certs/daosCA.crt
    cert: ${SCAFFOLD}/daosCA/certs/agent.crt
    key: ${SCAFFOLD}/daosCA/certs/agent.key
CONTROL:
  name: daos_server
  hostlist: ['localhost']
  port: 10001
  transport_config:
    allow_insecure: false
    ca_cert: ${SCAFFOLD}/daosCA/certs/daosCA.crt
    cert: ${SCAFFOLD}/daosCA/certs/admin.crt
    key: ${SCAFFOLD}/daosCA/certs/admin.key