SCAFFOLD: null
DAOS_ROOT: ${DAOS_ROOT}
CONF:
  SERVER: ${SCAFFOLD}/daos_server.yaml
  AGENT: ${SCAFFOLD}/daos_agent.yaml
  CONTROL: ${SCAFFOLD}/daos_control.yaml
SERVER:
  transport_config:
    client_cert_dir: ${SCAFFOLD}/daosCA
    ca_cert: ${SCAFFOLD}/daosCA/daosCA.crt
    cert: ${SCAFFOLD}/daosCA/server.crt
    key: ${SCAFFOLD}/daosCA/server.key
AGENT:
  transport_config:
    ca_cert: ${SCAFFOLD}/daosCA/daosCA.crt
    cert: ${SCAFFOLD}/daosCA/agent.crt
    key: ${SCAFFOLD}/daosCA/agent.key
CONTROL:
  transport_config:
    ca_cert: ${SCAFFOLD}/daosCA/daosCA.crt
    cert: ${SCAFFOLD}/daosCA/admin.crt
    key: ${SCAFFOLD}/daosCA/admin.key