SCAFFOLD: null
DAOS_SPACK:
  package_name: daos
DAOS_ROOT: ${SCAFFOLD}/daos_install
NAME: daos_server
PORT: 10001
SECURE: true
CONF:
  SERVER: ${SCAFFOLD}/daos_server.yaml
  AGENT: ${SCAFFOLD}/daos_agent.yaml
  CONTROL: ${SCAFFOLD}/daos_control.yaml
SERVER:
  access_points: ${SCAFFOLD}/server_hosts.txt
  provider: ofi+tcp
  telemetry_port: 9191
  control_log_file: ${SCAFFOLD}/daos_server.log
  transport_config:
    ca_cert: ${SCAFFOLD}/daosCA/certs/daosCA.crt
    cert: ${SCAFFOLD}/daosCA/certs/server.crt
    client_cert_dir: ${SCAFFOLD}/daosCA/certs
    key: ${SCAFFOLD}/daosCA/certs/server.key
  engines:
    -
      targets: 1
      first_core: 0
      nr_xs_helpers: 0
      fabric_iface: ens3
      fabric_iface_port: 31416
      log_file: ${SCAFFOLD}/daos_engine.0.log
      env_vars:
        - FI_SOCKETS_MAX_CONN_RETRY=1
        - FI_SOCKETS_CONN_TIMEOUT=2000
      storage:
        - class: ram
          scm_size: 1
          scm_mount: '${SCAFFOLD}/scm_test'
        - class: file
          bdev_size: 1
          bdev_list: ['${SCAFFOLD}/file_test']
AGENT:
  access_points: ${SCAFFOLD}/agent_hosts.txt
  transport_config:
    ca_cert: ${SCAFFOLD}/daosCA/certs/daosCA.crt
    cert: ${SCAFFOLD}/daosCA/certs/agent.crt
    key: ${SCAFFOLD}/daosCA/certs/agent.key
CONTROL:
  hostlist: ${SCAFFOLD}/control_hosts.txt
  transport_config:
    ca_cert: ${SCAFFOLD}/daosCA/certs/daosCA.crt
    cert: ${SCAFFOLD}/daosCA/certs/admin.crt
    key: ${SCAFFOLD}/daosCA/certs/admin.key
POOLS:
  - name: io500_pool
    size: 100G
    type: POSIX
CONTAINERS:
  - name: io500_container
    pool: io500_pool
