SCAFFOLD: null
DAOS_ROOT: ${DAOS_ROOT}
CONF:
  SERVER: ${SCAFFOLD}/daos_server.yaml
  AGENT: ${SCAFFOLD}/daos_agent.yaml
  CONTROL: ${SCAFFOLD}/daos_control.yaml
SERVER:
  name: daos_server
  access_points: ['localhost']
  port: 10001
  provider: ofi+tcp
  telemetry_port: 9191
  control_log_file: ${SCAFFOLD}/daos_server.log
  transport_config:
    allow_insecure: null
    ca_cert: ${SCAFFOLD}/daosCA/certs/daosCA.crt
    cert: ${SCAFFOLD}/daosCA/certs/server.crt
    client_cert_dir: ${SCAFFOLD}/daosCA/certs
    key: ${SCAFFOLD}/daosCA/certs/server.key
  engines:
    - storage:
        - class: ram
          scm_size: 1
          scm_mount: ${SCAFFOLD}/ram1
AGENT:
  name: daos_server
  access_points: ['localhost']
  port: 10001
  transport_config:
    allow_insecure: false
    ca_cert: ${SCAFFOLD}/daosCA/certs/daosCA.crt
    cert: ${SCAFFOLD}/daosCA/certs/agent.crt
    key: ${SCAFFOLD}/daosCA/certs/agent.key
CONTROL:
  name: daos_server
  hostlist: ['localhost']
  port: 10001
  transport_config:
    allow_insecure: false
    ca_cert: ${SCAFFOLD}/daosCA/certs/daosCA.crt
    cert: ${SCAFFOLD}/daosCA/certs/admin.crt
    key: ${SCAFFOLD}/daosCA/certs/admin.key