SCAFFOLD: null
DAOS_ROOT: ${DAOS_ROOT}
CONF:
  SERVER: ${SCAFFOLD}/daos_server.yaml
  AGENT: ${SCAFFOLD}/daos_agent.yaml
  CONTROL: ${SCAFFOLD}/daos_control.yaml
SERVER:
  transport_config:
    client_cert_dir: ${SCAFFOLD}/daosCA/certs
    ca_cert: ${SCAFFOLD}/daosCA/certs/daosCA.crt
    cert: ${SCAFFOLD}/daosCA/certs/server.crt
    key: ${SCAFFOLD}/daosCA/certs/server.key
AGENT:
  transport_config:
    ca_cert: ${SCAFFOLD}/daosCA/certs/daosCA.crt
    cert: ${SCAFFOLD}/daosCA/certs/agent.crt
    key: ${SCAFFOLD}/daosCA/certs/agent.key
CONTROL:
  transport_config:
    ca_cert: ${SCAFFOLD}/daosCA/certs/daosCA.crt
    cert: ${SCAFFOLD}/daosCA/certs/admin.crt
    key: ${SCAFFOLD}/daosCA/certs/admin.key