HOSTS: ${SHARED_DIR}/hostfile.txt
METADATA:
    HOSTS: 1
    META_DIR: ${PRIVATE_DIR}/orangefs_data/metadata
SERVER:
    HOSTS: 1
    PVFS2TAB: ${PRIVATE_DIR}/pvfs2tab
    STORAGE_DIR: ${PRIVATE_DIR}/orangefs_data/data
    LOG: ${PRIVATE_DIR}/orangefs_server.log
    STRIPE_SIZE: 65536
    DISTRIBUTION_NAME: simple_stripe
    PVFS2_PORT: 3334
    # protocol can be tcp or ib
    PVFS2_PROTOCOL: tcp
CLIENT:
    HOSTS: 1
    PVFS2TAB: ${PRIVATE_DIR}/pvfs2tab
    MOUNT_POINT: ${PRIVATE_DIR}/pvfs2-mount
