HOSTS: ['localhost']
NPROCS: 4
LABIOS_CONF: ${HOME}/labios_conf
#SIMPLE_WRITE, SIMPLE_READ, CM1_BASE, CM1_TABIOS, MONTAGE_BASE, MONTAGE_TABIOS, HACC_BASE, HACC_TABIOS, KMEANS_BASE, KMEANS_TABIOS, STRESS_TEST
TEST_CASE: SIMPLE_WRITE