SCAFFOLD: null
SCAFFOLD_SHARED: true
HOSTS: ['localhost']
LABIOS:
  WORKER_PATH: ${HOME}/test
  PFS_PATH: ${HOME}/pfs
  ASSIGNMENT_POLICY: RANDOM
  TS_NUM_WORKER_THREADS: 8
  CONF: ${SHARED_DIR}/labios_conf.yaml
WORKER:
  NPROCS: 1
  HOSTS: 1
WORKER_MANAGER:
  NPROCS: 1
  HOSTS: 1
TASK_SCHEDULER:
  NPROCS: 1
  HOSTS: 1
SERVER:
  NPROCS: 1
  HOSTS: 1
CLIENT:
  NPROCS: 1
  HOSTS: 1
MEMCACHED:
  MEMCACHED_SPACK:
    package_name: memcached
NATS:
  NATS_SPACK:
    package_name: nats-server
MEMCACHED_CLIENT:
  SCAFFOLD: ${SHARED_DIR}/memcached_client
  HOSTS: 1
  PORT: 11211
  LOG_PATH: ${SHARED_DIR}/memcached_client/log.txt
  MEMCACHED_ROOT: ${SHARED_DIR}/memcached_client/memcached_install
  MAX_ITEM_SIZE: 4m
MEMCACHED_SERVER:
  SCAFFOLD: ${SHARED_DIR}/memcached_server
  MEMCACHED_ROOT: ${SHARED_DIR}/memcached_server/memcached_install
  HOSTS: 1
  PORT: 11212
  LOG_PATH: ${SHARED_DIR}/memcached_server/log.txt
  MAX_ITEM_SIZE: 4m
NATS_CLIENT:
  SCAFFOLD: ${SHARED_DIR}/nats_client
  NATS_ROOT: ${SHARED_DIR}/nats_client/nats_install
  HOSTS: 1
  PORT: 4222
  LOG_PATH: ${SHARED_DIR}/nats_client/log.txt
NATS_SERVER:
  SCAFFOLD: ${SHARED_DIR}/nats_server
  NATS_ROOT: ${SHARED_DIR}/nats_server/nats_install
  HOSTS: 1
  PORT: 4223
  LOG_PATH: ${SHARED_DIR}/nats_server/log.txt