CONFIG_DIR: ${HOME}/jarvis-pipelines
CUR_PIPELINE: null
HOSTFILE: null
PRIVATE_DIR: /scratch/${USER}/jarvis-pipelines # local SSD
REPOS:
- name: builtin
  path: ${HOME}/jarvis-cd/builtin
SHARED_DIR: ${HOME}/jarvis-pipelines