CONFIG_DIR: ${HOME}/SCS_lab/jarvis_pipeline
CUR_PIPELINE: null
HOSTFILE: null
PRIVATE_DIR: /tmp/${USER}/jarvis
REPOS:
- name: builtin
  path: ${HOME}/SCS_lab/jarvis-cd/builtin
SHARED_DIR: /lus/grand/projects/VeloC/${USER}/SCS_lab/